#---------------------------------------------------------------------
server:
  port: 9060
#---------------------------------------------------------------------
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    status-page-url-path: /actuator/info #eureka注册中心的url link
    health-check-url-path: /actuator/health #健康检查的url
    hostname: localhost
    status-page-url: http://localhost:${server.port}/swagger-ui.html
#---------------------------------------------------------------------
info:
  version: 1.0.0
  app:
    name: ${spring.application.name}
#---------------------------------------------------------------------